name: biozenapp
region: nyc
services:
  - name: backend
    github:
      repo: 4beesdev/biozenapp
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      # Digital Ocean daje DATABASE_URL u formatu: postgresql://user:pass@host:port/dbname
      # Spring Boot očekuje: jdbc:postgresql://host:port/dbname
      # Koristimo pojedinačne varijable koje Digital Ocean automatski setuje
      - key: SPRING_DATASOURCE_URL
        scope: RUN_TIME
        value: jdbc:postgresql://${db.HOSTNAME}:${db.PORT}/${db.DATABASE}
      - key: SPRING_DATASOURCE_USERNAME
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        scope: RUN_TIME
        value: ${db.PASSWORD}
      # JWT - OBAVEZNO setovati u App-Level Environment Variables!
      - key: APP_JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${APP_JWT_SECRET}
      - key: APP_JWT_TTLMILLIS
        scope: RUN_TIME
        value: "604800000"
    routes:
      - path: /api

  - name: frontend
    github:
      repo: 4beesdev/biozenapp
      branch: main
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: Dockerfile
    build_command: ""  # Eksplicitno koristi Dockerfile, ne buildpack
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        scope: RUN_TIME
        value: ${backend.PUBLIC_URL}

databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    cluster_name: biozen-db
    db_name: biozenapp
    db_user: biozen

